Dockerfile and minor updates
beurtschipper/Depix pull request #10
Opened 2020-12-07 16:00 UTC by mgp25

This PR will add a Dockerfile and minor updates.

```
docker run -it --rm -v $(pwd):/data depix -p images/testimages/testimage3_pixels.png -s images/searchimages/debruinseq_notepad_Windows10_closeAndSpaced.png -o /data/output.png

INFO:root:Loading pixelated image from images/testimages/testimage3_pixels.png
INFO:root:Loading search image from images/searchimages/debruinseq_notepad_Windows10_closeAndSpaced.png
INFO:root:Finding color rectangles from pixelated space
INFO:root:Found 116 same color rectangles
INFO:root:86 rectangles left after moot filter
INFO:root:Found 1 different rectangle sizes
INFO:root:Finding matches in search image
INFO:root:Removing blocks with no matches
INFO:root:Splitting single matches and multiple matches
INFO:root:[10 straight matches | 76 multiple matches]
INFO:root:Trying geometrical matches on single-match squares
INFO:root:[15 straight matches | 71 multiple matches]
INFO:root:Trying another pass on geometrical matches
INFO:root:[17 straight matches | 69 multiple matches]
INFO:root:Writing single match results to output
INFO:root:Writing average results for multiple matches to output
INFO:root:Saving output image to: /data/output.png
```

2020-12-07 18:08 UTC, Saibamen requested changes
Missing `.dockerignore`

Please use https://github.com/beurtschipper/Depix/blob/main/.gitignore file list

2020-12-07 18:15 UTC, Saibamen commented on Dockerfile
> +FROM python:3
Please use `python:3.9-slim`:

```suggestion
FROM python:3.9-slim
```

https://hub.docker.com/layers/python/library/python/3.9-slim/images/sha256-5d300921213569f955c3954787298127d241c115f31fc92e87305c3e7a71c7ef?context=explore

`python:3.9-slim` compressed size is 40.78 MB
`python:3` size is 325.36 MB

2020-12-07 18:19 UTC, Saibamen requested changes

2020-12-07 18:19 UTC, Saibamen commented on Dockerfile
> +ENTRYPOINT ["python", "depix.py"]
`CMD` will be better?

2020-12-07 18:19 UTC, Saibamen commented on Dockerfile
> +RUN python -m pip install -r requirements.txt
Consider usage of `--upgrade pip`

2020-12-07 18:19 UTC, Saibamen commented on README.md
> +## Dockerfile
```suggestion
## Docker
```

2020-12-07 21:53 UTC, merged

2020-12-07 21:55 UTC, beurtschipper commented
Thanks! I've created a separate docker branch because I'm not a big fan of docker, but I like the addition. I'll also add the changes to the argparser to the main branch.

2020-12-08 01:28 UTC, mgp25 commented
Thanks! 😄

2020-12-08 23:16 UTC, Saibamen commented
@beurtschipper: Docker is must have in 2020...

Your project is open source. Just look at pull requests - 2 of them was about adding Docker support.

IMO better Docker support is in https://github.com/beurtschipper/Depix/pull/18 and https://github.com/beurtschipper/Depix/pull/18 should be merged into master branch

2021-03-15 08:09 UTC, toydotgame commented
> @beurtschipper: Docker is must have in 2020...
> 
> Your project is open source. Don't force other developers to install everything in their local machines and mix their environments.
> Just look at pull requests - 2 of them was about adding Docker support.
> 
> IMO better Docker support is in #18 and #18 should be merged into master branch

Docker is such a bloat to Depix!
Running
```sh
python -m pip install -r requirements.txt`
```
...is _so much better_ than the 8 scripts, 10 additional files, and 12+ headaches from Docker.
Depix uses _**1**_ dependency; and it sounds like one that most people would already have!